### ISSUE TITLE
Generated "const enum OrderDirection" clashes with isolatedModules

### ISSUE THREAD

**Issue by iainmerrick** [graphql-editor/graphql-zeus#316]
I'm using Zeus to generate bindings in one NPM package, and attempting to import and use them in another package.

I'm hitting type errors around this generated code:
```
export declare const enum OrderDirection {
    asc = "asc",
    desc = "desc"
}
```

The problem is that many clients configure TS with `isolatedModules: true`, which leads to a type error on import:

```
error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```

Using `"asc"` and `"desc"` directly in the client code doesn't work either, for reasons I can't quite fathom:

```
Type '"asc"' is not assignable to type 'OrderDirection | null | undefined'.
```

I don't fully understand why TypeScript can't be configured to handle this, but it seems like exporting const enums is generally considered bad practice:
- Here's a good writeup: https://ncjamieson.com/dont-export-const-enums/
- Unresolved discussion among the TS devs: https://github.com/microsoft/TypeScript/issues/40499

Can this be fixed by changing the exported declaration? I think this might work:
```
export type OrderDirection = "asc" | "desc"
```

**Comment by aexol** [comment]
A lot of people asked for const enums before instead of enums

**Comment by iainmerrick** [comment]
How about avoiding enums entirely and just making it a union of strings?

**Comment by aexol** [comment]
ok I'll try and test that with different projects and if it won't cause problems I will change it

**Comment by ValentinH** [comment]
For the reasons explained by @iainmerrick  and @aexol we were actually not able to use either  `enum` or `const enum` on our project. 

To avoid this, we patched this part and indeed used string unions. In the following screenshot, you can see our output on the left and the original Zeus output on the right:
![image](https://user-images.githubusercontent.com/2678610/188857084-91fe6f88-c8c4-4b0f-bc49-746d4cc1f2f3.png)

If this is something that looks good, I'm ready to do a PR to add this option using a flag. 🙂

**Comment by aexol** [comment]
This week I will upload new zeus with config and option to generate different enums. Sorry for delay

**Comment by klonwar** [comment]
> config and option to generate different enums

Is this option available in 5.4.2? Any CLI example?

**Comment by mountainmort** [comment]
Also running into this when trying to use the enums generated by Zeus in my NestJS API. The const enums that are generated can't be used as an enum type on Nest objects so I'm having to re-define the enum and map between the two. Would be great to see this compile option added.

**Comment by aexol** [comment]
enums done - now standard are normal enums and if you want constEnums you need a flag
